title: Honglei Xie
description: Just a Tiny Little Blog

url: http://HongleiXie.github.com/hongleixie.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: xhonglei2007@gmail.com

google_analytics: "UA-58263416-1"
